Implement Spring Security with in memory authentication
pavlokhomiak/cinema-project pull request #10
Opened 2020-10-29 15:35 UTC by pavlokhomiak

2020-10-29 16:21 UTC, TimoxaV commented on src/main/java/com/dev/cinema/model/dto/OrderRequestDto.java
>      private String userEmail;
You have null check in EmailValidator. So you don't need @NotNull annotation.

2020-10-29 16:23 UTC, TimoxaV commented on src/main/java/com/dev/cinema/model/dto/UserRequestDto.java
> +        fieldMatch = "repeatPassword")
It is better to add a custom message to let the client know what goes wrong.

2020-10-29 16:45 UTC, KseniiaMakarova requested changes

2020-10-29 16:45 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotations/EmailValidator.java
> +                .matches(EMAIL_REGEX);
```suggestion
        return field != null && field.matches(EMAIL_REGEX);
```

2020-10-29 16:45 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotations/PasswordValidator.java
> +                .getPropertyValue(fieldMatch);
if written on a single line, is it too long?

2020-10-29 16:45 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/annotations/PasswordValidator.java
> +        }
let's use ternary operator here

2020-10-29 16:45 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .csrf().disable();
let's have the same indentation everywhere

2020-10-29 16:45 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controller/OrderController.java
> +    public void completeOrder(@RequestBody @Valid OrderRequestDto dto) {
instead of OrderRequestDto - let's receive Authentication here

2020-10-29 16:45 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controller/UserController.java
> +    public UserResponseDto getByEmail(Authentication authentication) {
let's not change this method, it is not supposed to be refactored

2020-10-29 16:45 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/CinemaHallRequestDto.java
> +    @Min(10)
does it work without @Valid?

2020-10-29 16:45 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/OrderRequestDto.java
>  public class OrderRequestDto {
let's remove this dto

2020-10-30 14:25 UTC, KseniiaMakarova requested changes

2020-10-30 14:25 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/UserRequestDto.java
> +        message = "Password is not much")
Passwords do not match*

2020-10-30 14:25 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieRequestDto.java
> +    @NotNull
add @Valid annotation in the controller

2020-10-30 14:25 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionRequestDto.java
> +    @NotNull
same

2020-10-30 16:04 UTC, KseniiaMakarova approved these changes

2020-10-30 18:18 UTC, merged