HB-06
pavlokhomiak/cinema-project pull request #4
Opened 2020-10-08 21:47 UTC by pavlokhomiak

2020-10-08 22:00 UTC, DariiaPikul requested changes
Good job!

2020-10-08 22:00 UTC, dariiabutorina commented on src/main/java/com/dev/cinema/Main.java
> +        User user = userService.findByEmail("pawa@gmail.com").get();
How about making String EMAIL a constant variable?

2020-10-08 22:00 UTC, dariiabutorina commented on src/main/java/com/dev/cinema/dao/impl/ShoppingCartDaoImpl.java
> +    public ShoppingCart getByUser(User user) {
Let's make this an Optional

2020-10-09 07:14 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/ShoppingCartDaoImpl.java
> +    public ShoppingCart getByUser(User user) {
Це не є обов'язковим в даному випадку, можна залишити так

2020-10-09 07:14 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/ShoppingCartDaoImpl.java
> +                            + "left join fetch sc.user "
нам обов'язково робити left join для user?

2020-10-09 18:02 UTC, pavlokhomiak commented on src/main/java/com/dev/cinema/dao/impl/ShoppingCartDaoImpl.java
> +                            + "left join fetch sc.user "
не обовязково бо юзер ніколи не буде null якщо шопінгкарт існує?

2020-10-12 09:39 UTC, KseniiaMakarova approved these changes

2020-10-12 09:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +        System.out.println("SECOND " + shoppingCart);
let's use your variables `user` and `shoppingCart` instead of making new queries to the DB

2020-10-12 09:39 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/dao/impl/TicketDaoImpl.java
> +            session.persist(ticket);
let's be consistent and use the same session methods everywhere unless we have a reason to use a different method

2020-10-12 09:52 UTC, merged