Add Movie, MovieSession, Authentication Controller and DTO
pavlokhomiak/cinema-project pull request #8
Opened 2020-10-23 09:50 UTC by pavlokhomiak

2020-10-23 10:12 UTC, DariiaPikul requested changes

2020-10-23 10:12 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/controller/InjectController.java
> +//    }
?

2020-10-23 10:12 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/controller/MovieController.java
> +    @PostMapping("/add")
```suggestion
    @PostMapping
```

2020-10-23 10:12 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/controller/MovieSessionController.java
> +    @PostMapping("/add")
```suggestion
    @PostMapping
```

2020-10-23 10:12 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
>  import org.apache.log4j.Logger;
```suggestion
import java.util.Optional;
import org.apache.log4j.Logger;
```

2020-10-23 10:12 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/controller/MovieSessionController.java
> +            @RequestParam(name = "date") String date) {
```suggestion
            @RequestParam @RequestParam @DateTimeFormat(pattern = "dd.MM.yyyy") LocalDate date) {
```

2020-10-23 10:12 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/controller/MovieSessionController.java
> +        return movieSessionService.findAvailableSessions(id, localDate).stream()
```suggestion
        return movieSessionService.findAvailableSessions(id, date).stream()
```

2020-10-23 12:40 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/controller/MovieController.java
> +    @PostMapping("/add")
checklist
https://mate-academy.github.io/jv-program-fulltime/04_spring/checklist/hw_33.html

2020-10-23 12:40 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/controller/MovieController.java
> +    @GetMapping("/all")
same here

2020-10-23 12:40 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/model/dto/MovieSessionResponseDto.java
> +    private Long id;
what about CinemaHall

2020-10-23 12:40 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/model/dto/MovieSessionResponseDto.java
> +    private Movie movie;
you can jsut pass movieId instead of whole movie

2020-10-26 11:00 UTC, KseniiaMakarova requested changes

2020-10-26 11:00 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controller/MovieSessionController.java
> +    @GetMapping
let's add `("/available")` here
you are not fetching all movieSessions, just available ones

2020-10-26 12:08 UTC, KseniiaMakarova approved these changes

2020-10-26 16:29 UTC, merged